COMP = g++
CFLAGS = -Wall -Wextra

SOURCE = main.cpp
NAME = app

HEADERPATHS =
LIBPATH = 
LIBLINK = -L(LIBPATH) 

all: 
    (COMP) (CFLAGS) (HEADERPATHS) (LIBLINK) (SOURCE) -o (NAME)


.PHONY: clean
clean:
        rm (NAME)